---
title: CV
format:
  quarto-cv-pdf:
    pdf-engine: xelatex
author: Βιογραφικό Σημείωμα
test: Βιογραφικό Σημείωμα
# date: last-modified
phone: 
address: 
email: alexandros.rekkas@gmail.com
fontsize: 11pt
# fontfamily: quattrocento # default font LaTeX package https://tug.org/FontCatalogue/about.html
mainfont: DejaVuSans # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
github: rekkasa
orcid: 0000-0002-5352-943X # orcid identifier
#osf: ymqui # osf five character id
#twitter: twitter # twitter handle
# web: quarto.org
fontawesome: yes
nocite: '@*'
bibliography: 
  peer: peer_bib.bib
validate-yaml: false
csl: apa-annotated.csl
---

# Προσωπικά στοιχεία

> *Όνομα*: Αλέξανδρος

> *Επώνυμο*: Ρέκκας

> *Όνομα πατρός*: Κωνσταντίνος

> *Όνομα μητρός*: Ευγενία

> *Ημερομηνία γέννησης*: 30 Σεπτεμβρίου 1991

> *Τόπος γέννησης*: Θεσσαλονίκη

# Εκπαίδευση

*Erasmus Medical Center, Ολλανδία*, Διδακτορικό  
(**Συνημμένο D1**) \hfill 2017-2023

> *Τίτλος διατριβής*: [Beyond the average treatment effect: Risk-based approaches to medical
> decision making](https://pure.eur.nl/files/103693281/beyond-the-average-treatment-effect_-_652e948913b3f.pdf)

> *Επιβλέποντες καθηγητές*: Καθ. P.R. Rijnbeek, Καθ. E.W. Steyerberg, Αν. Καθ. D. van Klaveren


\

*KU Leuven, Βέλγιο*, M.Sc. Statistics (cum laude)  
(**Συνημμένο D2**) \hfill 2015-2017

> *Τίτλος διατριβής*: Robust model selection for generalized linear models

> *Επιβλέπων καθηγητής*: Καθ. S. Van Aelst

\

*Αριστοτέλειο Πανεπιστήμιο Θεσσαλονίκης, Ελλάδα*, Πτυχίο Μαθηματικών  
(**Συνημμένο D3**) \hfill 2009-2015


# Μεταδιδακτορική έρευνα (ερευνητικά προγράμματα)

1. [Enhancing the digital capabilities of cancer centres in Europe to improve prevention and care (eCAN Plus)](https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/projects-details/43332642/101219434/EU4H).

  - (**Συνημμένο S1**)
  - *Χρηματοδοτικό πλαίσιο*: EU4Health Programme (EU4H)
  - *Συμμετοχή*: από 1 Ιανουαρίου 2026 έως 31 Μαρτίου 2026
  - *Αντικείμενο*: Στατιστική ανάλυση βιοδεδομένων υγείας

2. [SYNTHIA: Synthetic data generation framework for integrated validation of use cases and AI healthcare applications](https://www.ihi-synthia.eu/).

  - (**Συνημμένο S1**)
  - *Χρηματοδοτικό πλαίσιο*: IHI Innovative Health Initiative
  - *Συμμετοχή*: από 1 Ιανουαρίου 2025 έως 31 Δεκεμβρίου 2025
  - *Αντικείμενο*: Στατιστική ανάλυση βιοδεδομένων υγείας

3. [European Digital Innovation Hub for Smart Health](https://smarthealth-edih.eu/en/homepag/)

  - (**Συνημμένο S1**)
  - *Χρηματοδοτικό πλαίσιο*: Πρόɣρɑμμɑ Digital Europe Programme (DEP) & ΕΣΠΑ 2021‐2027
  - *Συμμετοχή*: από 1 Απριλίου 2024 έως 31 Δεκεμβρίου 2024
  - *Αντικείμενο*: Στατιστική ανάλυση βιοδεδομένων υγείας

# Ερευνητικά προγράμματα πριν την απόκτηση του διδακτορικού

4. [European Health Data and Evidence Network](https://www.ehden.eu/) (EHDEN project)

  - (**Συνημμένο S2**)
  - *Χρηματοδοτικό πλαίσιο*: Innovative Medicines Initiative 2 Joint Undertaking
  - *Συμμετοχή*: από 1 Δεκεμβρίου 2019 έως 30 Νοεμβρίου 2023
  - *Αντικείμενο*: Διδακτορική έρευνα στην προσωποποιημένη ιατρική με τη χρήση
    δεδομένων πραγματικού κόσμου

# Πρακτική άσκηση

*P-95 Pharmacoepidemiology*  
(**Συνημμένο S3**) \hfill 6-7/2016

> *Επιβλέπουσα*: Δρ. Kaatje Bollaerts


# Διδασκαλία

1. Διδασκαλία των μαθημάτων "Στοχαστικές διαδικασίες", "Οικονομετρία" και
   "Στατιστικά Προγράμματα II" σε προπτυχιακούς φοιτητές του Τμήματος
   Στατιστικής του Πανεπιστημίου Δυτικής Μακεδονίας στα πλαίσια του προγράμματος
   "Απόκτηση ακαδημαϊκής εμπειρίας σε νέους επιστήμονες κατόχους διδακτορικού",
   εαρινό εξάμηνο 2025-2026.  
   (**Συνημμένο S4**)

1. Διδασκαλία των μαθημάτων "Εκπαιδευτική έρευνα", "Στατιστική στην εκπαιδευτική
   έρευνα" και "Ποσοτικές μέθοδοι" σε προπτυχιακούς φοιτητές του Παιδαγωγικού
   Τμήματος Νηπιαγωγών του Πανεπιστημίου Δυτικής Μακεδονίας στα πλαίσια του
   προγράμματος "Απόκτηση ακαδημαϊκής εμπειρίας σε νέους επιστήμονες κατόχους
   διδακτορικού", χειμερινό εξάμηνο 2025-2026.  
   (**Συνημμένο S4**)

1. Συμμετοχή στη διδασκαλία του μαθήματος "Advanced Analysis of Prognosis
Studies", χειμερινό-εαρινό εξάμηνο 2018-2019, Netherlands Institute for Health
Sciences, Erasmus MC, Rotterdam.

1. Tutorial με τίτλο "Population-Level Estimation" στο πλαίσιο του 2019 OHDSI
Symposium, North Bethesda, USA, 19 Σεπτεμβρίου 2019
[[link](https://www.ohdsi.org/2019-tutorial-population-level-estimation/)]

1. Επίβλεψη της τρίμηνης πρακτικής άσκησης του μεταπτυχιακού φοιτητή Gidius van
   de Kamp το 2023 με αντικείμενο "Developing a R-package for performing
   plasmode simulations using data mapped to the OMOP common data model"
   [[link](https://healthdatascience.nl/gidius-van-de-kamp-cv)]


# Ξένες γλώσσες

1. Αγγλικά: Επίπεδο C2 (**Συνημμένο S5**)
2. Γερμανικά: Επίπεδο B2 (**Συνημμένο S6**)
