---
title: CV
format:
  quarto-cv-pdf: default
author: Alexandros Rekkas
date: last-modified
phone: "{{< env PHONE >}}"
address: "{{< env ADDRESS >}}"
email: "{{< env EMAIL >}}"
fontsize: 11pt
fontfamily: quattrocento
github: rekkasa
orcid: 0000-0002-5352-943X
#osf: ymqui # osf five character id
#twitter: twitter # twitter handle
# web: quarto.org
fontawesome: yes
nocite: '@*'
bibliography: 
  peer: peer_bib.bib
validate-yaml: false
csl: apa-numeric.csl
---

# Personal information

\begin{tabular}{ l l l }
\textit{Name:} Alexandros & \textit{Father's Name:} Konstantinos & \textit{Date of Birth:} September 30th, 1991 \\
\textit{Surname:} Rekkas & \textit{Mother's Name:} Eugenia & \textit{Place of Birth:} Thessaloniki, Greece \\
\end{tabular}

# Education

*Erasmus Medical Center* \hfill Rotterdam, Netherlands \newline
Ph.D. Medical Informatics \hfill 2017-2023

> *Thesis*: [Beyond the average treatment effect: Risk-based approaches to medical decision making](https://pure.eur.nl/files/103693281/beyond-the-average-treatment-effect_-_652e948913b3f.pdf)

> *Supervisors*: Prof. P.R. Rijnbeek, Prof. E.W. Steyerberg, Dr. D. van Klaveren


*KU Leuven* \hfill Leuven, Belgium \newline
M.Sc. Statistics (cum laude) \hfill 2015-2017

> *Thesis*: Robust model selection for generalized linear models

> *Supervisor*: Prof. S. Van Aelst

*Aristotle University of Thessaloniki* \hfill Thessaloniki, Greece \newline
B.Sc. Mathematics \hfill 2009-2015

# Work experience

*Centre for Research and Technology Hellas* \hfill Thessaloniki, Greece \newline
Research associate \hfill 2024-present

> *Description*: As part of the [eHealth Lab](https://ehealth-lab.inab.certh.gr/) of the Institute of Applied
> Biosciences, the OHDSI National Node for Greece, I am responsible for the execution of statistical analyses on the
> OMOP databases. Also, I am the current core developer of the online platform of the Hellenic registry of patients with
> home mechanical ventilation [[link](https://hmv-registry.gr/)].

*Erasmus Medical Center* \hfill Rotterdam, Netherlands \newline
PhD Researcher\hfill 2017-2023

> *Description*: Carried out PhD research on the evaluation of treatment effect heterogeneity in observational healhcare
> data. In addition, worked on the development and validation of clinical prediction models. This resulted in the
> publication of several scientific articles, the development of R-packages and the deployment of Shiny applications.

*Leiden University Medical Center* \hfill Leiden, Netherlands \newline
PhD Researcher\hfill 2017-2019

> *Description*: Carried out PhD research on the evaluation of treatment effect heterogeneity in observational healhcare
> data. The main result of this work was the publication of a scientific literature review on the topic.

*P-95 Pharmacoepidemiology* \hfill Leuven, Belgium \newline
Internship \hfill 6-7/2016

> *Supervisor*: Dr. Kaatje Bollaerts

> *Description*: Assisted in the derivation of analytical expressions for all validity indices used to evaluate
> case-finding algorithms in observational databases. The aim was to derive all validity indices and the true prevalence
> of disease from observed prevalence and any two other parameters.

# Projects

*Risk stratified estimation*

> Developed and maintained the R-package *RiskStratifiedEstimation* used for carrying out risk-stratified evaluation of
> treatment effect heterogeneity in observational databases mapped to OMOP-CDM. Visit the project at
> [GitHub](https://github.com/ohdsi/RiskStratifiedEstimation). The package won the 2020 Best Contribution in Open-Source
> Analytics Development at the 2020 OHDSI Global Symposium
> [[link](https://www.ohdsi.org/2020-global-symposium-collaborator-showcase/)].

*Covid outcome prediction in the Emergency Department*

> Developed an online calculator in the form of a Shiny application for the
> [COPE prediction model](https://doi.org/10.1136/bmjopen-2021-051468). The calculator provided death and ICU admission
> risks within 28 days of hospital admission. Visit the project at [GitHub](https://github.com/mi-erasmusmc/COPE).

*Patient-level prediction*

> Contributed to the development of the R-package *PatientLevelPrediction*, part of the
> [HADES](https://ohdsi.github.io/Hades) suite of software. The package is used extensively for carrying out prediction
> tasks on observational databases mapped to OMOP-CDM. Visit the project at
> [GitHub](https://github.com/OHDSI/PatientLevelPrediction).

*EHDEN MegaStudy*

> As member of the Greek National Node of OHDSI, was responsible for executing the code of the EHDEN Network study on
> drug shortages on the database of the Papageorgiou General Hospital of Thessaloniki, Greece and sharing the results
> with collaborators. The database is mapped to OMOP-CDM.



# Skills

> *Programming*: R, Python, SQL

> *Languages*: Greek (native speaker), English (C2), German (B2)

# Research programmes

1. Synthetic data generation framework for integrated validation of use cases
   and AI healthcare applications.
   ([SYNTHIA](https://www.ihi.europa.eu/projects-results/project-factsheets/synthia):
   IHI Innovative Health Initiative project), 2024-2029, Participation Januuary
   2025 --- present.

2. European Digital Innovation Hub for Smart Health: Precision Medicine and Innovative E-health Services.
   ([smartHealth](https://smarthealth-edih.eu/en/homepag/): Digital Europe Programme & ESPA 2021-2027. Participated
   April 2024 till December 2024.

3. European Health Data and Evidence Network ([EHDEN](https://www.ehden.eu/) project), 2018-2024. Participated from
   December 1st, 2019 till November 30th, 2023.

4. Accelarated Development of Vaccine Benefit-risk Collaboration in Europe
   ([ADVANCE](https://www.imi.europa.eu/projects-results/project-factsheets/advance) project), 2013-2019. Participation
   June 1st till July 31st, 2016.


# Teaching

1. Tutor at the 2024 Training School on "Impact of Meta-analyses on Clinical Practice" organised by The European Network
   on Osteoarthritis [[link](https://netwoark.eu/event/training-school-impact-of-meta-analyses-on-clinical-practice/)].

2. Invited speaker at the 2024 Summer School of the M.Sc. programme in Biomedical Engineering of the Aristotle
   University of Thessaloniki. Title of the course was "Machine learning applications using OMOP-CDM"
   [[link](https://bme.web.auth.gr/en/summer-school/summer-school-2024/)].

3. Supervised the three-month internship of master student Gidius van de Kamp in 2023. The internship aimed at
   developing a R-package for performing plasmode simulations using data mapped to the OMOP common data model. This
   resulted in poster presentation 12 below.

4. Tutorial with title "Population-Level Estimation" at the 2019 OHDSI Symposium, North Bethesda, USA, September 19th,
   2019 [[link](https://www.ohdsi.org/ohdsi-news-updates/2019-symposium-tutorials/)].

5. Teaching assistance for the course "Advanced Analysis of Prognosis Studies", Winter-Spring 2018-2019, Netherlands
   Institute for Health Sciences, Erasmus MC, Rotterdam.




# Publications

::: {#refs-peer}
:::

# Conferences and symposia

1. *Poster presentation*: Risk Stratified Analysis of Treatment Effect in
Electronic Health Records. **Alexandros Rekkas**, Peter R. Rijnbeek, Jenna Reps,
David Van Klaveren. First Annual European OHDSI Symposium, Rotterdam, The
Netherlands, March 23rd, 2018 [[link](https://www.ohdsi-europe.org/images/symposium-2018/posters/31-Alexandros-Rekkas.pdf)]

2. *Poster presentation*: Exploring Heterogeneity of Treatment Effects:
Develompent of a New OHDSI Analytics Package and Demonstration Using the
Gastrointestinal Bleeding Risk of Celecoxib. **Alexandros Rekkas**, Peter R.
Rijnbeek, James Weaver, Martijn Schuemie, Jenna Reps, David Van Klaveren. 2018
OHDSI Symposium, North Bethesda, USA, October 12th, 2018 [[link](https://www.ohdsi.org/wp-content/uploads/2018/10/2018-Poster-Session-FINAL-200-black-and-white-copies-double-sided-stapled.pdf)]

3. *Poster presentation*: Development of a R-package to Explore Heterogeneity of
Treatment Effects: A Demonstration in Patients with Hypertension. **Alexandros
Rekkas**, David van Klaveren, Peter R. Rijnbeek. Second Annual European OHDSI
Symposium, Rotterdam, The Netherlands, March 29th, 2019 [[link](https://www.ohdsi-europe.org/images/symposium-2019/posters/24_Alexandros_Rekkas.pdf)]

4. *Poster presenation*: Assessing Heterogeneity of Hypertension Treatment
Effects: A Risk Modeling Approach. **Alexandros Rekkas**, David van Klaveren,
Peter R. Rijnbeek. 2019 OHDSI Symposium, North Bethesda, USA, September 16th,
2019 [[link](https://www.ohdsi.org/2019-us-symposium-showcase-39/)]

5. *Poster presentation*: Large-scale evaluation of treatment effect
heterogeneity in hypertension. **Alexandros Rekkas**, David van Klaveren, Peter
R. Rijnbeek. 2020 OHDSI Global Symposium, Online Symposium, October 19th, 2020 
[[link](https://www.ohdsi.org/2020-global-symposium-showcase-63/)].

6. *Poster presentation*: Treatment heterogeneity in comparative effectiveness
of teriparatide vs bisphosphonates: multi-database cohort study, **Alexandros
Rekkas**, Annika M. Jodicke, David van Klaveren, Daniel Prieto-Alhambra, Peter
R. Rijnbeek. 2021 OHDSI Global Symposium, Online Symposium, September 14th, 2021
[[link](https://www.ohdsi.org/2021-global-symposium-showcase-95/)]

7. *Poster presentation*: Trends in the development and validation of
patient-level prediction models using electronic health record data: a
systematic review, Cynthia Yang, Jan A. Kors, Solomon Ioannou, Luis H. John,
Aniek F. Markus, **Alexandros Rekkas**, Maria de Ridder, Tom Seinen, Ross D.
Williams, Peter R. Rijnbeek. 2021 OHDSI Global Symposium, Online Symposium,
September 14th, 2021 [[link](https://www.ohdsi.org/2021-global-symposium-showcase-55/)]

8. *Oral presentation*: Assessing treatment effect heterogeneity using the
RiskStratifiedEstimation R-package, **Alexandros Rekkas**, David van Klaveren,
Peter R. Rijnbeek, Third European OHDSI Symposium, Rotterdam, The Netherlands,
June 24th, 2022 [[link](https://www.ohdsi-europe.org/images/symposium-2022/posters/arekkas_poster_-_Alexandros_Rekkas.pdf)]
[[video](https://www.youtube.com/watch?v=wYgk-qn-teo)]

9. *Oral presentation*: Predicting individualized treatment effects using
baseline risk: A simulation study, **Alexandros Rekkas**, Peter R. Rijnbeek,
David M. Kent, Ewout W. Steyerberg, David van Klaveren. 43rd Annual Conference
of the International Society of Biostatistics, Newcastle, UK, August 21-25, 2022 \
Pages 31 and 94 in the book of abstracts
[[link](https://iscb.international/wp-content/uploads/2022/08/ISCB_2022-PROGRAMME-final.pdf)].

10. *Oral presentation*: Treatment heterogeneity in comparative effectiveness
ofTeriparatide versus Bisphosphonates: Multi-database cohort study, **Alexandros
Rekkas**, Annika Joedicke, David van Klaveren, Daniel Prieto-Alhambra, Peter R.
Rijnbeek. 38th International Conference on Pharmacoepidemiology, Copenhagen,
Denmark, August 26-28, 2022. \
Page 57 in the ICPE 2022 Final Program [[link](https://pharmacoepi.org/pub/?id=A15839AD-B6E4-D28E-1C20-FA5A5B1D2B50)]

11. *Poster presentation*: A standardized framework for risk-based assessment of
treatment effect heterogeneity in observational healthcare databases,
**Alexandros Rekkas**, David van Klaveren, Patrick B. Ryan, Ewout W. Steyerberg,
David M. Kent, Peter R. Rijnbeek. SMDM 18th Biennial European Conference,
Berlin, Germany, May 21-23, 2023. \
Poster session 2 [[link](https://www.smdmmeeting.org/meeting-program/program-overview/)]

12. *Poster presentation*: PlasmodeSim: R package to simulate data with known
treatment assignment and outcome generating processes, Gidius van de Kamp,
**Alexandros Rekkas** , Fourth European OHDSI Symposium, Rotterdam, The
Netherlands, July 3rd, 2023 [[link](https://www.ohdsi-europe.org/images/symposium-2023/posters/plasmode_simulation_gvk_ar_-_Alexandros_Rekkas.pdf)]

13. *Oral presentation*: Evaluation of treatment effect heterogeneity in the
LEGEND-Hypertension study, **Alexandros Rekkas**, David van Klaveren, Jenna M.
Reps, Peter R. Rijnbeek, Fourth European OHDSI Symposium, Rotterdam, The
Netherlands, July 3rd, 2023 [[link](https://www.ohdsi-europe.org/images/symposium-2023/posters/rekkas_legend_htn_hte_poster_-_Alexandros_Rekkas.pdf)] [[video](https://www.youtube.com/watch?v=wgiIHdf5P4Y)]

14. *Poster presentation*: Conversion of the Papageorgiou General Hospital EHR to the OMOP Common data Model
Grigoris Papapostolou, Achilleas Chytas, **Alexandros Rekkas**, Maria Bigaki, Demetrios Zeimpekis,
Lampros Dermentzoglou George Tortopidis, Pantelis Natsiavas 
[[link](https://www.ohdsi-europe.org/images/symposium-2024/Posters/natsiavas_conversion_papageorgiou_general_hospital_omop%20-%20Alexandros%20Rekkas.pdf)].

15. *Poster presentation*: Real-World Data in Greece: Mapping the Papageorgiou General Hospital data to the
OMOP Common Data Mode. Grigoris Papapostolou, Achilleas Chytas, **Alexandros Rekkas**, Maria Bigaki, Demetrios Zeimpekis,
Lampros Dermentzoglou, George Tortopidis, Pantelis Natsiavas. 34th Medical Informatics Europe Conference
[[link](https://convin.gr/assets/files/misc/MIE2024_PROGRAMME_fin.pdf)].
