---
title: CV
format:
  quarto-cv-pdf:
    pdf-engine: xelatex
author: Βιογραφικό Σημείωμα
test: Βιογραφικό Σημείωμα
# date: last-modified
phone: 
address: 
email: alexandros.rekkas@gmail.com
fontsize: 11pt
# fontfamily: quattrocento # default font LaTeX package https://tug.org/FontCatalogue/about.html
mainfont: DejaVuSans # if you want to use a different locally installed font
#CJKmainfont: Noto Sans CJK JP # locally installed Asian character font, must use with xelatex
github: rekkasa
orcid: 0000-0002-5352-943X # orcid identifier
#osf: ymqui # osf five character id
#twitter: twitter # twitter handle
# web: quarto.org
fontawesome: yes
nocite: '@*'
bibliography: 
  peer: peer_bib.bib
validate-yaml: false
csl: apa-annotated.csl
---

# Προσωπικά στοιχεία

> *Όνομα*: Αλέξανδρος

> *Επώνυμο*: Ρέκκας

> *Όνομα πατρός*: Κωνσταντίνος

> *Όνομα μητρός*: Ευγενία

> *Ημερομηνία γέννησης*: 30 Σεπτεμβρίου 1991

> *Τόπος γέννησης*: Θεσσαλονίκη

# Εκπαίδευση

*Erasmus Medical Center, Ολλανδία*, Διδακτορικό \hfill 2017-2023

> *Τίτλος διατριβής*: [Beyond the average treatment effect: Risk-based approaches to medical
> decision making](https://pure.eur.nl/files/103693281/beyond-the-average-treatment-effect_-_652e948913b3f.pdf)

> *Επιβλέποντες καθηγητές*: Καθ. P.R. Rijnbeek, Καθ. E.W. Steyerberg, Αν. Καθ. D. van Klaveren

\

*KU Leuven, Βέλγιο*, M.Sc. Statistics (cum laude) \hfill 2015-2017

> *Τίτλος διατριβής*: Robust model selection for generalized linear models

> *Επιβλέπων καθηγητής*: Καθ. S. Van Aelst

\

*Αριστοτέλειο Πανεπιστήμιο Θεσσαλονίκης, Ελλάδα*, Πτυχίο Μαθηματικών \hfill 2009-2015

# Πρακτική άσκηση

*P-95 Pharmacoepidemiology* \hfill 6-7/2016

> *Επιβλέπουσα*: Δρ. Kaatje Bollaerts


# Μεταδιδακτορική έρευνα (ερευνητικά προγράμματα)

1. [SYNTHIA: Synthetic data generation framework for integrated validation of use cases and AI healthcare applications](https://www.ihi-synthia.eu/).

  - *Χρηματοδοτικό πλαίσιο*: IHI Innovative Health Initiative
  - *Συμμετοχή*: από 1 Ιανουαρίου 2025 έως 31 Δεκεμβρίου 2025
  - *Αντικείμενο*: Στατιστική ανάλυση βιοδεδομένων υγείας

2. [European Digital Innovation Hub for Smart Health](https://smarthealth-edih.eu/en/homepag/)

  - *Χρηματοδοτικό πλαίσιο*: Πρόɣρɑμμɑ Digital Europe Programme (DEP) & ΕΣΠΑ 2021‐2027
  - *Συμμετοχή*: από 1 Απριλίου 2024 έως 31 Δεκεμβρίου 2024
  - *Αντικείμενο*: Στατιστική ανάλυση βιοδεδομένων υγείας

# Ερευνητικά προγράμματα

3. [European Health Data and Evidence Network](https://www.ehden.eu/) (EHDEN project)

  - *Χρηματοδοτικό πλαίσιο*: Innovative Medicines Initiative 2 Joint Undertaking
  - *Συμμετοχή*: από 1 Δεκεμβρίου 2019 έως 30 Νοεμβρίου 2023
  - *Αντικείμενο*: Διδακτορική έρευνα στην προσωποποιημένη ιατρική με τη χρήση
    δεδομένων πραγματικού κόσμου

4. [Accelarated Development of Vaccine Benefit-risk Collaboration in
Europe](https://www.imi.europa.eu/projects-results/project-factsheets/advance)
(ADVANCE project), 2013-2019.

  - *Χρηματοδοτικό πλαίσιο*: IHI Innovative Health Initiative
  - *Συμμετοχή*: από 1 Ιουνίου 2016 έως 31 Ιουλίου 2016
  - *Αντικείμενο*: Πρατική άσκηση ως στατιστικός για την αξιολόγηση αλγορίθμων
    εύρεσης περιστατικών με τη χρήση ιατρικών δεδομένων πραγματικού κόσμου


# Διδασκαλία

1. Διδασκαλία των μαθημάτων "Εκπαιδευτική έρευνα", "Στατιστική στην εκπαιδευτική
   έρευνα" και "Ποσοτικές μέθοδοι" σε προπτυχιακούς φοιτητές του Παιδαγωγικού
   Τμήματος Νηπιαγωγών του Πανεπιστημίου Δυτικής Μακεδονίας στα πλαίσια του
   προγράμματος "Απόκτηση ακαδημαϊκής εμπειρίας σε νέους επιστήμονες κατόχους
   διδακτορικού", χειμερινό εξάμηνο 2025-2026.

1. Συμμετοχή στη διδασκαλία του μαθήματος "Advanced Analysis of Prognosis
Studies", χειμερινό-εαρινό εξάμηνο 2018-2019, Netherlands Institute for Health
Sciences, Erasmus MC, Rotterdam.

1. Tutorial με τίτλο "Population-Level Estimation" στο πλαίσιο του 2019 OHDSI
Symposium, North Bethesda, USA, 19 Σεπτεμβρίου 2019
[[link](https://www.ohdsi.org/2019-tutorial-population-level-estimation/)]

1. Επίβλεψη της τρίμηνης πρακτικής άσκησης του μεταπτυχιακού φοιτητή Gidius van
   de Kamp το 2023 με αντικείμενο "Developing a R-package for performing
   plasmode simulations using data mapped to the OMOP common data model"
   [[link](https://healthdatascience.nl/gidius-van-de-kamp-cv)]

   

# Δημοσιεύσεις σε διεθνή περιοδικά με σύστημα κριτών

::: {#refs-peer}
:::

# Διεθνή συνέδρια και συμπόσια

i. *Poster presentation*: Risk Stratified Analysis of Treatment Effect in
Electronic Health Records. **Alexandros Rekkas**, Peter R. Rijnbeek, Jenna Reps,
David Van Klaveren. First Annual European OHDSI Symposium, Rotterdam, The
Netherlands, March 23rd, 2018
[[link](https://www.ohdsi-europe.org/images/symposium-2018/posters/31-Alexandros-Rekkas.pdf)]

ii. *Poster presentation*: Exploring Heterogeneity of Treatment Effects:
Develompent of a New OHDSI Analytics Package and Demonstration Using the
Gastrointestinal Bleeding Risk of Celecoxib. **Alexandros Rekkas**, Peter R.
Rijnbeek, James Weaver, Martijn Schuemie, Jenna Reps, David Van Klaveren. 2018
OHDSI Symposium, North Bethesda, USA, October 12th, 2018
[[link](https://www.ohdsi.org/wp-content/uploads/2018/10/2018-Poster-Session-FINAL-200-black-and-white-copies-double-sided-stapled.pdf)]

iii. *Poster presentation*: Development of a R-package to Explore Heterogeneity of
Treatment Effects: A Demonstration in Patients with Hypertension. **Alexandros
Rekkas**, David van Klaveren, Peter R. Rijnbeek. Second Annual European OHDSI
Symposium, Rotterdam, The Netherlands, March 29th, 2019
[[link](https://www.ohdsi-europe.org/images/symposium-2019/posters/24_Alexandros_Rekkas.pdf)]

iv. *Poster presenation*: Assessing Heterogeneity of Hypertension Treatment
Effects: A Risk Modeling Approach. **Alexandros Rekkas**, David van Klaveren,
Peter R. Rijnbeek. 2019 OHDSI Symposium, North Bethesda, USA, September 16th,
2019
[[link](https://www.ohdsi.org/2019-us-symposium-showcase-39/)]

v. *Poster presentation*: Large-scale evaluation of treatment effect
heterogeneity in hypertension. **Alexandros Rekkas**, David van Klaveren, Peter
R. Rijnbeek. 2020 OHDSI Global Symposium, Online Symposium, October 19th, 2020 
[[link](https://www.ohdsi.org/2020-global-symposium-showcase-63/)]\
**\* ** **Recipient of 2020 Best Contribution in Open-Source Analytics Development [[link](https://www.ohdsi.org/2020-global-symposium-collaborator-showcase/)]**

vi. *Poster presentation*: Treatment heterogeneity in comparative effectiveness
of teriparatide vs bisphosphonates: multi-database cohort study, **Alexandros
Rekkas**, Annika M. Jodicke, David van Klaveren, Daniel Prieto-Alhambra, Peter
R. Rijnbeek. 2021 OHDSI Global Symposium, Online Symposium, September 14th, 2021
[[link](https://www.ohdsi.org/2021-global-symposium-showcase-95/)]

vii. *Poster presentation*: Trends in the development and validation of
patient-level prediction models using electronic health record data: a
systematic review, Cynthia Yang, Jan A. Kors, Solomon Ioannou, Luis H. John,
Aniek F. Markus, **Alexandros Rekkas**, Maria de Ridder, Tom Seinen, Ross D.
Williams, Peter R. Rijnbeek. 2021 OHDSI Global Symposium, Online Symposium,
September 14th, 2021
[[link](https://www.ohdsi.org/2021-global-symposium-showcase-55/)]

viii. *Oral presentation*: Assessing treatment effect heterogeneity using the
RiskStratifiedEstimation R-package, **Alexandros Rekkas**, David van Klaveren,
Peter R. Rijnbeek, Third European OHDSI Symposium, Rotterdam, The Netherlands,
June 24th, 2022 
[[link](https://www.ohdsi-europe.org/images/symposium-2022/posters/arekkas_poster_-_Alexandros_Rekkas.pdf)]
[[video](https://www.youtube.com/watch?v=wYgk-qn-teo)]

ix. *Oral presentation*: Predicting individualized treatment effects using
baseline risk: A simulation study, **Alexandros Rekkas**, Peter R. Rijnbeek,
David M. Kent, Ewout W. Steyerberg, David van Klaveren. 43rd Annual Conference
of the International Society of Biostatistics, Newcastle, UK, August 21-25, 2022 \
Σελίδες 31 και 94 στο πρόγραμμα και βιβλίο περιλήψεων
([link](https://iscb.international/wp-content/uploads/2022/08/ISCB_2022-PROGRAMME-final.pdf)).

x. *Oral presentation*: Treatment heterogeneity in comparative effectiveness
of Teriparatide versus Bisphosphonates: Multi-database cohort study, **Alexandros
Rekkas**, Annika Joedicke, David van Klaveren, Daniel Prieto-Alhambra, Peter R.
Rijnbeek. 38th International Conference on Pharmacoepidemiology, Copenhagen,
Denmark, August 26-28, 2022 
[[link](https://onlinelibrary.wiley.com/doi/epdf/10.1002/pds.5518)]

xi. *Poster presentation*: A standardized framework for risk-based assessment of
treatment effect heterogeneity in observational healthcare databases,
**Alexandros Rekkas**, David van Klaveren, Patrick B. Ryan, Ewout W. Steyerberg,
David M. Kent, Peter R. Rijnbeek. SMDM 18th Biennial European Conference,
Berlin, Germany, May 21-23, 2023
Poster session 2
([link](https://www.smdmmeeting.org/meeting-program/program-overview/)). 

xii. *Oral presentation*: Evaluation of treatment effect heterogeneity in the
LEGEND-Hypertension study, **Alexandros Rekkas**, David van Klaveren, Jenna M.
Reps, Peter R. Rijnbeek, Fourth European OHDSI Symposium, Rotterdam, The
Netherlands, July 3rd, 2023 
[[link](https://www.ohdsi-europe.org/images/symposium-2023/posters/rekkas_legend_htn_hte_poster_-_Alexandros_Rekkas.pdf)] [[video](https://www.youtube.com/watch?v=wgiIHdf5P4Y)]

xiii. *Poster presentation*: PlasmodeSim: R package to simulate data with known
treatment assignment and outcome generating processes, Gidius van de Kamp,
**Alexandros Rekkas** , Fourth European OHDSI Symposium, Rotterdam, The
Netherlands, July 3rd, 2023 
[[link](https://www.ohdsi-europe.org/images/symposium-2023/posters/plasmode_simulation_gvk_ar_-_Alexandros_Rekkas.pdf)]


# Δεξιότητες

> *Προγραμματισμός*: R, Python

> *Ξένες γλώσσες*: Αγγλικά (C2), Γερμανικά (B2)


# Τεκμηρίωση καταλληλότητας

1. Γνωστικό υπόβαθρο και ερευνητική δραστηριότητα συναφή με το αντικείμενο της
Στατιστικής και τις θεματικές ενότητες του μαθήματος.
2. Μεταπτυχιακές σπουδές στη Στατιστική (M.Sc., KU Leuven, βαθμός cum laude)
εστιασμένες στην Bιοστατιστική και μεταπτυχιακή διατριβή με θέμα την επιλογή και
αξιολόγηση γενικευμένων γραμμικών μοντέλων.
3. Διδακτορική διατριβή στο Erasmus MC (2017–2023) επικεντρωμένη στην αξιοποίηση
στατιστικών μεθόδων για την εκτίμηση ετερογένειας της θεραπευτικής επίδρασης και
την υποστήριξη ιατρικών αποφάσεων. Κατά τη διάρκεια εκπόνησης της διατριβής
αναπτύχθηκαν και αξιολογήθηκαν προγνωστικά μοντέλα (κατά κύριο λόγο μοντέλα
λογιστικής παλινδρόμησης και ανάλυσης επιβίωσης) σε διάφορους ιατρικούς τομείς
(καρκίνος δέρματος, COVID-19).
4. Δημοσιευμένο σε περιοδικά υψηλού κύρους με εφαρμογή στατιστικών τεχνικών όπως
λογιστική παλινδρόμηση, μοντέλα Cox, ROC καμπύλες, και αξιολόγηση διαγνωστικών
και προγνωστικών μοντέλων, οι οποίες αποτελούν βασικά στοιχεία της διδακτέας
ύλης του μαθήματος.
5. Εμπειρία στη διδασκαλία σχετικών θεμάτων τόσο σε προπτυχιακά (απόκτηση
ακαδημαϊκής εμπειρίας χειμερινό εξάμηνο 2025-2026) όσο μεταπτυχιακά προγράμματα
σπουδών και σε διεθνή επιστημονικά συμπόσια.
